apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    name: myapp
    type: front-end
spec:
  template:
    metadata:
      name: my-app
      labels:
        name: my-apppod
    spec:
      containers:
        - name: nginx-container
          image: nginx
  selector:
    matchLabels:
      name: my-apppod
  replicas: 3